on:
  push:
    branches:
      - ci-release
    tags:
      - v*
  workflow_dispatch:

name: create-release

jobs:
  build:
    name: Create release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      # - uses: dtolnay/rust-toolchain@stable

      # - name: Build project
      #   run: cargo build --release

      # - name: Create workflow
      #   run: |
      #     cp target/release/pirate-weather workflow
      #     zip -rqj pirate-weather.alfredworkflow workflow/*

      - name: Create release
        id: create-release
        run: |
          UPLOAD_URL="$(
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/releases \
              -d '{"tag_name":"${{ github.ref }}","target_commitish":"${{ github.ref }}","name":"${{ github.ref }}","body":"# ${{ github.ref }}","draft":true,"prerelease":false,"generate_release_notes":false}' \
            | jq --raw-output .upload_url)"
          # UPLOAD_URL=${UPLOAD_URL/'{?name,label}'/?name=pirate-weather.alfredworkflow}
          # echo $UPLOAD_URL
          touch pirate-weather.alfredworkflow
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/zip" \
            "${UPLOAD_URL/'{?name,label}'/?name=pirate-weather.alfredworkflow}" \
            --data-binary "@pirate-weather.alfredworkflow"
